### ISSUE TITLE
As a backend dev, I want to research and review search and sort algorithms so I can modify priority searches and organize groups more optimally

### ISSUE THREAD

**Issue by High-Tek-Toaster** [snowminc/Groupformer#39]
1. Hill climbing
2. State based searching
3. Genetic algorithms
4. Constraint satisfaction algorithms
5. BFS and DFS
6. Greedy
7. Random search
8. Stimulated annealing
9. K-means clustering ***

**Comment by Brunswick-Khorasan** [comment]
Required to complete #19

**Comment by KristianMischke** [comment]
Did about an hour of cursory reading into the different algorithms at a high level.

Most of the options we put to explore seem like they would be more work than we'd need to find even a mostly optimal solution.

[Random-restart hill climbing](https://en.wikipedia.org/wiki/Hill_climbing#Variants) seems like what Dr. Johnson was referring to when he said we could start with a basic algorithm. It tries a random input set (in our case student groupings) then scores it. It repeats m times computing a new input set and comparing to and keeping the best score.

Doing a genetic algorithm isn't too far off random restart hill climbing because we'd be testing many different input sets against each other and keep the best of them... the main difference would be there would be multiple rounds and they would be breeded/mutated to add new samples. Genetic algorithms are pretty easy to implement, and I've done them before.

K-means clustering seems promising. I'm having a little bit of a hard time figuring out exactly how we would parameterize the inputs for the algorithm, so that would require more digging into the algorithm details.
