### ISSUE TITLE
As an instructor, I want to be able to input a variety of projects and descriptions so that there are choices for the participants to work on.

### ISSUE THREAD

**Issue by Brunswick-Khorasan** [snowminc/Groupformer#5]
Allow instructors to add projects and descriptions for them

**Comment by Brunswick-Khorasan** [comment]
This is the whole point of the tool, for assigning participants to groups, so they must have a variety of choices to choose from.

**Comment by Brunswick-Khorasan** [comment]
Fuller description, from SRS:

The instructor should be able to input projects into a web form when setting up the project grouping, as shown below. Each project should allow the instructor to input a name and a description. There should also be some button that allows the addition of a new project to the list of assignable projects, allowing an arbitrary number of projects to be added to the grouping.

**Comment by KristianMischke** [comment]
mockup:
![image](https://user-images.githubusercontent.com/4390379/108923827-826d9380-7607-11eb-8b04-0b79f13bc6b0.png)

**Comment by KristianMischke** [comment]
Tests are located at app/groupformer/setup_screen/tests.py

Test command:
```
cd app/groupformer
python manage.py test setup_screen
```

NOTE for running tests: You need to download the selenium webdriver and put it in your PATH variable.
- Download: https://chromedriver.chromium.org/downloads
- Make sure this matches your chrome version
- Update PATH Environment Variable:
- Windows:
    - Save `chromedriver.exe` to a path such as `C:\Program Files\Selenium`
    - Press the windows button and search 'advanced system settings'
    - Click 'Environment Variables'
    - Edit your User or System `PATH` variable adding the directory you chose

Further Note: Currently an issue with Chrome v89 that will be fixed in v90 but is currently in beta.
Selenium will spew some warning messages, but this doesn't effect the integration tests aside from
clogging the terminal output.
- https://stackoverflow.com/questions/65080685/usb-usb-device-handle-win-cc1020-failed-to-read-descriptor-from-node-connectio
