### ISSUE TITLE
As an instructor, I want to be able to input other attributes and questions so that participants will be matched accordingly.

### ISSUE THREAD

**Issue by Brunswick-Khorasan** [snowminc/Groupformer#9]
These attributes and questions will help group the participants together in ways as specified by the instructor. The instructor will be able to determine whether the attributes will group participants with similar responses to be on the same team or on opposing teams. This would allow a variety of participants or a similarity based on the attribute.
e.g. extroverts/introverts could be put together or backend and front end developers could be put together. Question example, “Have you had experience doing web dev?”

**Comment by Brunswick-Khorasan** [comment]
Fuller description, from SRS:

These attributes and questions will help group the participants together in ways as specified by the instructor. The instructor will be able to determine whether the attributes will group participants with similar responses to be on the same team or on opposing teams. This would allow a variety of participants or a similarity based on the attribute.
e.g. extroverts/introverts could be put together or backend and front end developers could be put together. Question example, “Have you had experience doing web dev?” 

The instructor will be able to enter in the preferred attributes for the users to select options from. The instructor will also be able to click a radio button to match similar responses or to match non similar responses. The attributes are not project specific. When presented to the user, the attributes will be in the form a multiple choice option or a slider to represent a range.

**Comment by KristianMischke** [comment]
mockup:
![image](https://user-images.githubusercontent.com/4390379/108923910-a7fa9d00-7607-11eb-9055-64c9e29b2239.png)

**Comment by KristianMischke** [comment]
Tests are located at app/groupformer/setup_screen/tests.py

Test command:
```
cd app/groupformer
python manage.py test setup_screen
```

NOTE for running tests: You need to download the selenium webdriver and put it in your PATH variable.
- Download: https://chromedriver.chromium.org/downloads
- Make sure this matches your chrome version
- Update PATH Environment Variable:
- Windows:
    - Save `chromedriver.exe` to a path such as `C:\Program Files\Selenium`
    - Press the windows button and search 'advanced system settings'
    - Click 'Environment Variables'
    - Edit your User or System `PATH` variable adding the directory you chose

Further Note: Currently an issue with Chrome v89 that will be fixed in v90 but is currently in beta.
Selenium will spew some warning messages, but this doesn't effect the integration tests aside from
clogging the terminal output.
- https://stackoverflow.com/questions/65080685/usb-usb-device-handle-win-cc1020-failed-to-read-descriptor-from-node-connectio
